version: "3.0"
services:

  web:
    image: 295295069944.dkr.ecr.eu-central-1.amazonaws.com/charla-cd-nginx-ssl:REPLACE_APP_IMAGE
    volumes:
      - nginx-certs:/etc/letsencrypt/
    depends_on:
      - web_nossl
    ports:
      - 443:443

volumes:
  nginx-certs:
    external: true