version: "3.0"
services:

  web_nossl:
    image: nginx-charla:latest
    depends_on:
      - app
    ports:
      - 80:80

  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: charlasAreFun
      MYSQL_DATABASE: charla
      MYSQL_USER: charla
      MYSQL_PASSWORD: charlaPassword
    ports:
      - 3306:3306
