version: "3.0"
services:

  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: charlasAreFun
      MYSQL_DATABASE: charla
      MYSQL_USER: charla
      MYSQL_PASSWORD: charlaPassword
    ports:
      - 3306:3306

  app:
    image: 295295069944.dkr.ecr.eu-central-1.amazonaws.com/charla-cd-demo:latest
    restart: always

  web:
    image: nginx:latest
    restart: always
    ports:
      - 80:80